import express, { Request, Response, NextFunction } from 'express'
import cors from 'cors'
import jwt from 'jsonwebtoken'
import dotenv from 'dotenv'
import QRCode from 'qrcode'
import path from 'path'
import bcrypt from 'bcrypt'
import { fileURLToPath } from 'url'
import { collection, query, where, getDocs, doc, setDoc, getDoc, updateDoc, addDoc } from 'firebase/firestore'
import { db } from './firebase.js'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../../.env') })

const app = express()
const PORT = process.env.PORT || 3001
const JWT_SECRET = process.env.JWT_SECRET || 'dev-secret-key'
const APP_URL = process.env.APP_URL || 'http://localhost:5173'
const SCAN_TOKEN_EXPIRY_SECONDS = 30
const TOKEN_REFRESH_INTERVAL = SCAN_TOKEN_EXPIRY_SECONDS * 1000

// Types
export interface UserPayload {
  id: string;
  email: string;
  role: string;
}

declare module 'express-serve-static-core' {
  interface Request {
    user?: UserPayload;
  }
}

// Middleware
app.use(cors())
app.use(express.json())

// =============================================================================
// AUTH ENDPOINTS
// =============================================================================

const handleRegister = async (req: Request, res: Response): Promise<any> => {
  const { email, name, password, role } = req.body

  if (!email || !email.endsWith('@u.nus.edu')) {
    return res.status(400).json({
      error: 'Please use a valid NUS email (@u.nus.edu)',
    })
  }
  
  if (!password || password.length < 6) {
    return res.status(400).json({ error: 'Password must be at least 6 characters long' })
  }

  try {
    const usersRef = collection(db, 'users');
    const q = query(usersRef, where('email', '==', email));
    const querySnapshot = await getDocs(q);
    
    if (!querySnapshot.empty) {
      return res.status(400).json({ error: 'User with this email already exists' })
    }

    // Hash password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(password, saltRounds);

    // Set role to string ('student' or 'organiser') and gracefully default to student
    const finalRole = (role === 'student' || role === 'organiser') ? role : 'student';

    // Create user with AutoID generated by addDoc
    const newUser = {
      email,
      name: name || email.split('@')[0],
      role: finalRole,
      passwordHash: hashedPassword,
      createdAt: new Date().toISOString()
    };
    
    const docRef = await addDoc(collection(db, 'users'), newUser);
    const userForToken = { id: docRef.id, ...newUser };

    // Issue JWT
    const token = jwt.sign(
      { id: userForToken.id, email: userForToken.email, role: userForToken.role },
      JWT_SECRET,
      { expiresIn: '24h' }
    )

    // Remove passwordHash before sending back
    const { passwordHash, ...safeUser } = userForToken;
    res.json({ token, user: safeUser })
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error during registration' })
  }
}

const handleLogin = async (req: Request, res: Response): Promise<any> => {
  const { email, password } = req.body

  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required' })
  }

  try {
    const usersRef = collection(db, 'users');
    const q = query(usersRef, where('email', '==', email));
    const querySnapshot = await getDocs(q);
    
    if (querySnapshot.empty) {
      return res.status(401).json({ error: 'Invalid email or password' })
    }

    const userDoc = querySnapshot.docs[0];
    const user = { id: userDoc.id, ...userDoc.data() } as any;

    if (!user.passwordHash) {
       return res.status(401).json({ error: 'Invalid user credentials configuration. Please register again.' })
    }

    // Verify Password
    const match = await bcrypt.compare(password, user.passwordHash)
    if (!match) {
      return res.status(401).json({ error: 'Invalid email or password' })
    }

    // Issue JWT
    const token = jwt.sign(
      { id: user.id, email: user.email, role: user.role },
      JWT_SECRET,
      { expiresIn: '24h' }
    )

    const { passwordHash, ...safeUser } = user;
    res.json({ token, user: safeUser })
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Server error during login' })
  }
}

app.post('/api/auth/register', handleRegister);
app.post('/api/auth/login', handleLogin);

// Verify token middleware
const verifyToken = (req: Request, res: Response, next: NextFunction): any => {
  const token = req.headers.authorization?.split(' ')[1]

  if (!token) {
    return res.status(401).json({ error: 'No token provided' })
  }

  try {
    const decoded = jwt.verify(token, JWT_SECRET) as UserPayload
    req.user = decoded
    next()
  } catch (error) {
    res.status(401).json({ error: 'Invalid token' })
  }
}

// =============================================================================
// JWT SCAN TOKEN SERVICE
// =============================================================================

const generateScanToken = (eventId: string): string => {
  return jwt.sign(
    { eventId, type: 'scan' },
    JWT_SECRET,
    { expiresIn: `${SCAN_TOKEN_EXPIRY_SECONDS}s` }
  )
}

const generateScanUrl = (eventId: string): string => {
  const token = generateScanToken(eventId)
  return `${APP_URL}/scan?token=${token}&eventId=${eventId}`
}

const verifyScanToken = (token: string, eventId: string) => {
  try {
    const payload = jwt.verify(token, JWT_SECRET) as any
    if (payload.type !== 'scan') return { valid: false, error: 'Invalid token type' }
    if (payload.eventId !== eventId) return { valid: false, error: 'Token event mismatch' }
    return { valid: true, payload }
  } catch (error: any) {
    if (error.name === 'TokenExpiredError') return { valid: false, error: 'Token expired' }
    return { valid: false, error: 'Invalid token' }
  }
}

// SSE stream: EventSource can't set headers, so accept token via query param
app.get('/api/events/:eventId/qr-stream', async (req: Request, res: Response): Promise<any> => {
  const eventId = req.params.eventId as string;
  const authToken = req.query.token as string;

  if (!authToken) return res.status(401).json({ error: 'No token provided' })

  try {
    const decoded = jwt.verify(authToken, JWT_SECRET) as UserPayload
    req.user = decoded
  } catch {
    return res.status(401).json({ error: 'Invalid token' })
  }

  try {
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) {
      return res.status(404).json({ error: 'Event not found' })
    }

    const event = eventDoc.data();
    if (event.organiserId !== req.user?.id) {
      return res.status(403).json({ error: 'Not authorised' })
    }

    res.setHeader('Content-Type', 'text/event-stream')
    res.setHeader('Cache-Control', 'no-cache')
    res.setHeader('Connection', 'keep-alive')

    const sendQR = async () => {
      const scanUrl = generateScanUrl(eventId)
      const qrData = {
        scanUrl,
        refreshAt: Date.now() + TOKEN_REFRESH_INTERVAL,
        expiresAt: Date.now() + TOKEN_REFRESH_INTERVAL + 5000,
      }

      try {
        const qrCode = await QRCode.toDataURL(scanUrl)
        res.write(`data: ${JSON.stringify({ ...qrData, qrCode })}\n\n`)
      } catch (err) {
        res.write(`data: ${JSON.stringify(qrData)}\n\n`)
      }
    }

    sendQR()
    const interval = setInterval(sendQR, TOKEN_REFRESH_INTERVAL)

    req.on('close', () => {
      clearInterval(interval)
      res.end()
    })
  } catch(e) {
    console.error(e);
    res.status(500).json({ error: 'Server error' });
  }
})

app.post('/api/events/:eventId/generate-token', verifyToken, async (req: Request, res: Response): Promise<any> => {
  const eventId = req.params.eventId as string;

  try {
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })

    const event = eventDoc.data();
    if (event.organiserId !== req.user?.id) return res.status(403).json({ error: 'Not authorised' })

    const scanUrl = generateScanUrl(eventId)
    const expiresAt = Date.now() + TOKEN_REFRESH_INTERVAL

    try {
      const qrDataUrl = await QRCode.toDataURL(scanUrl, { width: 512 })
      return res.json({ scanUrl, expiresAt, qrDataUrl })
    } catch {
      return res.json({ scanUrl, expiresAt })
    }
  } catch(e) {
    console.error(e);
    res.status(500).json({ error: 'Server error' });
  }
})

// =============================================================================
// EVENT ENDPOINTS
// =============================================================================

app.post('/api/events', verifyToken, async (req: Request, res: Response): Promise<any> => {
  const { title, category, venue, startTime, endTime, expectedAttendees } = req.body

  if (!title || !category || !venue) {
    return res.status(400).json({ error: 'Missing required fields' })
  }

  const eventId = `event-${Date.now()}`
  const event = {
    id: eventId,
    title,
    category,
    venue,
    startTime: new Date(startTime).toISOString(),
    endTime: new Date(endTime).toISOString(),
    expectedAttendees: expectedAttendees || 50,
    organiserId: req.user?.id,
    status: 'draft',
    checkInPhase: null,
    checkOutPhase: null,
    createdAt: new Date().toISOString(),
  }

  await setDoc(doc(db, 'events', eventId), event);
  res.json(event)
})

app.get('/api/events', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventsSnapshot = await getDocs(collection(db, 'events'));
    const allEvents = eventsSnapshot.docs.map(d => d.data());
    const userEvents = allEvents.filter((e) => {
      const isOrganiser = e.organiserId === req.user?.id
      const isFuture =
        new Date(e.startTime) > new Date() || e.status === 'ongoing' || e.status === 'completed'
      return isOrganiser || isFuture
    })

    res.json(userEvents)
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

app.get('/api/events/:eventId', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventId = req.params.eventId as string;
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) {
      return res.status(404).json({ error: 'Event not found' })
    }

    const event = eventDoc.data();
    
    // Get attendance stats
    const attendancesSnap = await getDocs(query(collection(db, 'attendances'), where('eventId', '==', eventId)));
    const attendances_for_event = attendancesSnap.docs.map(d => d.data());

    res.json({
      ...event,
      attendanceCount: attendances_for_event.length,
      attendances: attendances_for_event,
    })
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

app.patch('/api/events/:eventId/start', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventId = req.params.eventId as string;
    const docRef = doc(db, 'events', eventId);
    const eventDoc = await getDoc(docRef);
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })
    
    const event = eventDoc.data();
    if (event.organiserId !== req.user?.id) return res.status(403).json({ error: 'Not authorised' })

    const updates = {
      status: 'ongoing',
      checkInPhase: {
        startedAt: new Date().toISOString(),
        endedAt: null,
      }
    }

    await updateDoc(docRef, updates);
    res.json({ ...event, ...updates })
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

app.patch('/api/events/:eventId/end', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventId = req.params.eventId as string;
    const docRef = doc(db, 'events', eventId);
    const eventDoc = await getDoc(docRef);
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })
    
    const event = eventDoc.data();
    if (event.organiserId !== req.user?.id) return res.status(403).json({ error: 'Not authorised' })

    const updates: any = { status: 'completed' }
    if (event.checkInPhase) {
      updates.checkInPhase = {
        ...event.checkInPhase,
        endedAt: new Date().toISOString()
      };
    }

    await updateDoc(docRef, updates);
    res.json({ ...event, ...updates })
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

// =============================================================================
// SCAN & ATTENDANCE ENDPOINTS
// =============================================================================

app.post('/api/scan', verifyToken, async (req: Request, res: Response): Promise<any> => {
  const { token, eventId, deviceId } = req.body

  try {
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })
    const event = eventDoc.data();

    const verification = verifyScanToken(token, eventId)
    if (!verification.valid) return res.status(400).json({ error: verification.error })

    const attSnap = await getDocs(query(
      collection(db, 'attendances'), 
      where('eventId', '==', eventId),
      where('userId', '==', req.user?.id),
      where('phase', '==', 'check-in')
    ));

    if (!attSnap.empty) {
      return res.status(409).json({
        error: 'Already checked in',
        timestamp: attSnap.docs[0].data().timestamp,
      })
    }

    let status = 'attended'
    if (event.checkInPhase) {
      const eventStart = new Date(event.startTime)
      if (new Date() > new Date(eventStart.getTime() + 15 * 60000)) {
        status = 'late'
      }
    }

    const attendanceId = `attendance-${Date.now()}`
    const attendance = {
      id: attendanceId,
      eventId,
      userId: req.user?.id,
      userEmail: req.user?.email,
      phase: 'check-in',
      timestamp: new Date().toISOString(),
      deviceId: deviceId || null,
      status
    }

    await setDoc(doc(db, 'attendances', attendanceId), attendance);

    res.json({ success: true, attendance })
  } catch(e) {
    console.error(e);
    res.status(500).json({ error: 'Server error' });
  }
})

// =============================================================================
// ATTENDANCE ANALYTICS
// =============================================================================

app.get('/api/events/:eventId/attendances', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventId = req.params.eventId as string;
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })
    const event = eventDoc.data();

    if (event.organiserId !== req.user?.id) return res.status(403).json({ error: 'Not authorised' })

    const attSnap = await getDocs(query(collection(db, 'attendances'), where('eventId', '==', eventId)));
    const eventAttendances = attSnap.docs.map(d => d.data());

    const summary = {
      totalScanned: eventAttendances.length,
      expected: event.expectedAttendees,
      percentage: Math.round((eventAttendances.length / event.expectedAttendees) * 100) || 0,
      byStatus: {
        attended: eventAttendances.filter((a) => a.status === 'attended').length,
        late: eventAttendances.filter((a) => a.status === 'late').length,
      },
      suspiciousActivity: detectSuspiciousScans(eventAttendances),
    }

    res.json({ attendances: eventAttendances, summary })
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

const detectSuspiciousScans = (attendances: any[]) => {
  const suspicious: any[] = []
  const deviceMap: Record<string, any[]> = {}
  attendances.forEach((a) => {
    if (!a.deviceId) return
    if (!deviceMap[a.deviceId]) deviceMap[a.deviceId] = []
    deviceMap[a.deviceId].push(a)
  })

  Object.entries(deviceMap).forEach(([deviceId, scans]) => {
    if (scans.length > 1) {
      suspicious.push({
        type: 'MULTIPLE_SCANS_SAME_DEVICE',
        deviceId,
        scanCount: scans.length,
        userIds: scans.map((s) => s.userId),
      })
    }
  })
  return suspicious
}

// =============================================================================
// CSV EXPORT
// =============================================================================

app.get('/api/events/:eventId/export-csv', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventId = req.params.eventId as string;
    const eventDoc = await getDoc(doc(db, 'events', eventId));
    if (!eventDoc.exists()) return res.status(404).json({ error: 'Event not found' })
    const event = eventDoc.data();

    if (event.organiserId !== req.user?.id) return res.status(403).json({ error: 'Not authorised' })

    const attSnap = await getDocs(query(collection(db, 'attendances'), where('eventId', '==', eventId)));
    const eventAttendances = attSnap.docs.map(d => d.data());

    const csv = [
      ['Email', 'Timestamp', 'Status', 'Phase'].join(','),
      ...eventAttendances.map((a) => [a.userEmail, a.timestamp, a.status || 'attended', a.phase].join(',')),
    ].join('\n')

    res.setHeader('Content-Type', 'text/csv')
    res.setHeader('Content-Disposition', `attachment; filename="event-${eventId}-attendances.csv"`)
    res.send(csv)
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

// =============================================================================
// STUDENT DASHBOARD
// =============================================================================

app.get('/api/me/attendances', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const attSnap = await getDocs(query(collection(db, 'attendances'), where('userId', '==', req.user?.id)));
    const userAttendancesRaw = attSnap.docs.map(d => d.data());

    // Fetch events for these attendances
    const userAttendances = await Promise.all(userAttendancesRaw.map(async (a) => {
      let eventTitle = 'Unknown', eventCategory = 'Unknown';
      const evtDoc = await getDoc(doc(db, 'events', a.eventId));
      if (evtDoc.exists()) {
        const e = evtDoc.data();
        eventTitle = e.title;
        eventCategory = e.category;
      }
      return { ...a, eventTitle, eventCategory };
    }));

    const badges = computeBadges(userAttendances)

    res.json({
      attendances: userAttendances,
      stats: {
        totalAttended: userAttendances.length,
        categoryCounts: groupByCategory(userAttendances),
        badges,
      },
    })
  } catch(e) {
    console.error(e);
    res.status(500).json({ error: 'Server error' });
  }
})

const groupByCategory = (attendances: any[]) => {
  const counts: Record<string, number> = {}
  attendances.forEach((a) => {
    if (a.eventCategory) counts[a.eventCategory] = (counts[a.eventCategory] || 0) + 1
  })
  return counts
}

const computeBadges = (attendances: any[]) => {
  const badges: any[] = []
  if (attendances.length >= 5) {
    badges.push({ name: 'Community Builder', icon: '🏢', description: 'Attended 5+ events' })
  }
  const eveningEvents = attendances.filter((a) => {
    const hour = new Date(a.timestamp).getHours()
    return hour >= 18 || hour < 6
  })
  if (eveningEvents.length >= 3) {
    badges.push({ name: 'Night Owl', icon: '🌙', description: 'Attended 3+ evening events' })
  }
  const categories = groupByCategory(attendances)
  Object.entries(categories).forEach(([cat, count]) => {
    if (count >= 5) {
      badges.push({ name: `${cat} Enthusiast`, icon: '⭐', description: `Attended 5+ ${cat} events` })
    }
  })
  return badges
}

// =============================================================================
// ORGANISER DASHBOARD
// =============================================================================

app.get('/api/organiser/summary', verifyToken, async (req: Request, res: Response): Promise<any> => {
  try {
    const eventsSnap = await getDocs(query(collection(db, 'events'), where('organiserId', '==', req.user?.id)));
    const organisedEvents = eventsSnap.docs.map(d => d.data());

    const summary = await Promise.all(organisedEvents.map(async (event) => {
      const attSnap = await getDocs(query(collection(db, 'attendances'), where('eventId', '==', event.id)));
      const count = attSnap.docs.length;
      return {
        ...event,
        attendanceCount: count,
        attendanceRate: Math.round((count / (event.expectedAttendees || 1)) * 100) + '%',
      }
    }));

    res.json(summary)
  } catch(e) {
    res.status(500).json({ error: 'Server error' });
  }
})

// =============================================================================
// HEALTH CHECK
// =============================================================================

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date() })
})

// Start server
app.listen(PORT, () => {
  console.log(`🎯 Attendify server running on http://localhost:${PORT}`)
  console.log(`📚 Connected to Firebase!`)
  console.log(`📚 Mock login via /api/auth/login. Can pass {email, role}`)
})
